# Intro to Keras: Neural Networks for Digit Classification
* Getting started with Keras: https://keras.io/
* Sequential model guide: https://keras.io/getting-started/sequential-model-guide/

In [29]:
import pickle # used to save and restore python objects
import gzip
import numpy as np

# Load the dataset
f = gzip.open('mnist.pkl.gz', 'rb')
train_set, valid_set, test_set = pickle.load(f, encoding = 'latin1')
f.close()

# gather intelligence on the data
print(type(train_set))
print(type(test_set))

<class 'tuple'>
<class 'tuple'>


In [30]:
# take a closer look
print("Inputs:")
print(train_set[0])
print("Inputs shape is " + str(train_set[0].shape))
print("Input type is " + str(type(train_set[0])))
print("Labels:")
print(train_set[1])
print("Labels shape is" + str(train_set[1].shape))
print("Labels type is " + str(type(train_set[1])))


Inputs:
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
Inputs shape is (50000, 784)
Input type is <class 'numpy.ndarray'>
Labels:
[5 0 4 ..., 8 4 8]
Labels shape is(50000,)
Labels type is <class 'numpy.ndarray'>


In [32]:
import keras

train_x = train_set[0]
train_y = keras.utils.to_categorical(train_set[1], num_classes=10)
test_x = test_set[0]
test_y = keras.utils.to_categorical(test_set[1], num_classes=10)

# let's see result of categorizing the outputs
print(test_y[:5])

[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]


In [33]:
from keras.models import Sequential

model = Sequential()

In [39]:
from keras.layers import Dense, Activation

model.add(Dense(units=500, input_dim=784))
model.add(Activation('relu'))
model.add(Dense(units=250))
model.add(Activation('relu'))
model.add(Dense(units=10))
model.add(Activation('softmax'))

In [40]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

In [41]:
model.fit(train_x, train_y, epochs=5, batch_size=32)

Epoch 1/5
50000/50000 [==============================] - 9s - loss: 0.9560 - acc: 0.9274       

In [42]:
loss_and_metrics = model.evaluate(test_x, test_y, batch_size=128)

 9472/10000 [===========================>..] - ETA: 0s

In [43]:
loss_and_metrics

[0.13263440186455847, 0.9657]